name: helmetDetection
channels:
  - defaults
dependencies:
  - pyserial=3.5
  - numpy=1.26.0
  - supervision=0.15.0
  - ultralytics=8.0.196
  - opencv-python=4.8.1.78
  - paho-mqtt=1.6.1
  - python>=3.11.5
